-- Migration: drop legacy DW log tables now replaced by AuditPort
-- Rollback strategy: restore from backup or recreate empty tables if needed
-- Preconditions: confirm no consumers; take full backup before execution

BEGIN;

-- Example legacy log tables; adjust to actual catalog if names differ
DROP TABLE IF EXISTS dw_access_log CASCADE;
DROP TABLE IF EXISTS dw_batch_log CASCADE;
DROP TABLE IF EXISTS dw_export_log CASCADE;
DROP TABLE IF EXISTS dw_audit_shadow CASCADE;

-- Optionally retain empty stub for compatibility (uncomment if needed)
-- CREATE TABLE dw_export_log (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
--   note TEXT
-- );

COMMIT;
